Arithmetic Operations

In [2]:
import numpy as np

In [3]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10]) # both arrays size should be same for arithmetic operations

In [4]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [5]:
a1-a2

array([-5, -5, -5, -5, -5])

In [6]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [7]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [8]:
a1 // a2

array([0, 0, 0, 0, 0])

In [9]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

Broadcasting

In [10]:
l=[10,20,30,40]
l1=[]
for i in l:
    l1.append(i+10)
print(l1)

[20, 30, 40, 50]


In [11]:
arr=np.array(l)
arr+10

array([20, 30, 40, 50])

In [13]:
arr2=np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [14]:
arr2 + 20

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45]])

Deep and Shallow Copy

In [15]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [18]:
slice=a[:5]
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [ ]:
a # in lists whenever we slicing any portion of it.. it effects the original list where as in Arrays we are slicing any portion of array it creates different location/space in RAM so original array doesn't effected by slicing.This is the Concept of Shallow Copy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [21]:
a[4:6] * 10

array([50, 60])

In [22]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
a
b=a # here total array 'a' is copied by 'b' 

In [24]:
b[0]=100
b

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [ ]:
a # so both 'a' and 'b' have same location that's why changes in array 'b' effects array 'a'

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [26]:
a1=np.arange(1,21)
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [28]:
a1
b1=a1.copy() # this enables Shallow Copy so the changes in array 'b1' doesn't effect on array 'a1'

In [29]:
b1[1]=200
b1

array([  1, 200,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [30]:
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Matrix Operations

In [31]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])

In [33]:
A


array([[1, 2],
       [3, 4]])

In [34]:
B

array([[5, 6],
       [7, 8]])

In [ ]:
A @ B # Dot product of Matrix

array([[19, 22],
       [43, 50]])

In [36]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [ ]:
A . T # Transpose of an Matrix

array([[1, 3],
       [2, 4]])

Stacking Array

In [44]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.array([9,10,11,12])

In [45]:
np.vstack((a,b,c)) # vertical stack

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [46]:
np.hstack((a,b,c)) # horizontal stack

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
np.column_stack((a,b,c)) # column stack

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

Splitting Array

In [49]:
d=np.arange(16).reshape(4,4)
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [50]:
np.hsplit(d,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [51]:
np.vsplit(d,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]